version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "3000:3000"

  oracles:
    build:
      context: .
      dockerfile: Dockerfile_oracles
    environment:
      - API_KEY=your_api_key
    depends_on:
      - backend

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
